window.productsData = [
  { name: "Humanoid G1 (Base/EDU)", image: "assets/products_shop_images/Humanoid_G1__BaseEDU__3.png", category: "Educational" },
  { name: "Humanoid H1", image: "assets/products_shop_images/Humanoid_H1_7.png", category: "Specialty" },
  { name: "Humanoid Oli", image: "assets/products_shop_images/Humanoid_Oli_1.png", category: "Specialty" },
  { name: "Humanoid R1", image: "assets/products_shop_images/Humanoid_R1.png", category: "Specialty" },
  { name: "Humanoid Mini Hi", image: "assets/products_shop_images/Humanoid_Mini_Hi_1.png", category: "Educational" },
  { name: "Mini pi Bipedal Robot", image: "assets/products_shop_images/Mini_π_Bipedal_Robot_1.png", category: "Educational" },

  { name: "Robodog B2", image: "assets/products_shop_images/Robodog_B2.png", category: "Specialty" },
  { name: "Robodog (B2/B2-W)", image: "assets/products_shop_images/Robodog__B2B2-W__1.png", category: "Specialty" },
  { name: "Robodog Go1", image: "assets/products_shop_images/Robodog_Go1_1.png", category: "Educational" },
  { name: "Robodog (Go2/Go2-W)", image: "assets/products_shop_images/Robodog__Go2Go2-W__1.png", category: "Specialty" },
  { name: "Robodog AlienGo", image: "assets/products_shop_images/Robodog_AlienGo_1.png", category: "Industrial" },
  { name: "Tron 1", image: "assets/products_shop_images/Tron_1_1.png", category: "Specialty" },

  { name: "Dual Arm Compound Robot", image: "assets/products_shop_images/Dual_Arm_Compound_Robot.png", category: "Industrial" },
  { name: "Base Chassis", image: "assets/products_shop_images/Base_Chassis_1.png", category: "Industrial" },
  { name: "Disinfectant Mini Robot", image: "assets/products_shop_images/Disinfectant_Mini_Robot_1.png", category: "Service" },
  { name: "Conveyor Robot", image: "assets/products_shop_images/Conveyor_Robot.png", category: "Industrial" },
  { name: "Delivery Robot (closed type)", image: "assets/products_shop_images/Delivery_Robot__closed_type__1.png", category: "Service" },
  { name: "Factory Delivery Robot", image: "assets/products_shop_images/Factory_Delivery_Robot_1.png", category: "Service" },

  { name: "Hermes Chassis", image: "assets/products_shop_images/Hermes Chassis_1.png", category: "Industrial" },
  { name: "Mars Smartbot", image: "assets/products_shop_images/Mars_Smartbot_1.png", category: "Service" },
  { name: "Hotel Robot", image: "assets/products_shop_images/Hotel_Robot_1.png", category: "Service" },
  { name: "Healthcare Robot", image: "assets/products_shop_images/Healthcare_Robot.png", category: "Service" },
  { name: "Heavy Load AMR", image: "assets/products_shop_images/Heavy_Load_AMR_1.png", category: "Industrial" },
  { name: "L Lift AMR", image: "assets/products_shop_images/L Lift AMR_2.jpg", category: "Industrial" },

  { name: "Smart Forklift", image: "assets/products_shop_images/Smart_Forklift.png", category: "Industrial" },
  { name: "Sub Lift Robot", image: "assets/products_shop_images/Sub_Lift_Robot_1.png", category: "Industrial" },
  { name: "Water 2", image: "assets/products_shop_images/Water 2_1.png", category: "Service" },

  { name: "Dex. Hand (RM56S2B) 2L/2R", image: "assets/products_shop_images/Dex._Hand__RM56S2B__2L2R_1.png", category: "Accessories" },
  { name: "Gripper (ERG32-150)", image: "assets/products_shop_images/Gripper__ERG32-150.png", category: "Accessories" },
  { name: "Gripper (EVS08)", image: "assets/products_shop_images/Gripper__EVS08_1.png", category: "Accessories" },
  { name: "Gripper (AG-160-95)", image: "assets/products_shop_images/Gripper__AG-160-95__1.png", category: "Accessories" },
  { name: "Gripper (RGS2-050)", image: "assets/products_shop_images/Gripper__RG52-050.png", category: "Accessories" },
  { name: "Gripper (RGI-100-30)", image: "assets/products_shop_images/Gripper__RGI-100-30.png", category: "Accessories" },

  { name: "Camera (RM-MVQ)", image: "assets/products_shop_images/Camera_RM-MVQ__1.png", category: "Accessories" },
  { name: "Robotic Arm (ECO62-B)", image: "assets/products_shop_images/Robotic_Arm__ECO62-B.png", category: "Industrial" },
  { name: "Robotic Arm (ECO65-6F)", image: "assets/products_shop_images/Robotic_Arm__ECO65-6F.png", category: "Industrial" },
  { name: "Robotic Arm (ECO65-B)", image: "assets/products_shop_images/Robotic_Arm__ECO65-B.png", category: "Industrial" },
  { name: "Robotic Arm (GEN72-B)", image: "assets/products_shop_images/Robotic_Arm__GEN72-B.png", category: "Industrial" },
  { name: "Robotic Arm (RM65-6F)", image: "assets/products_shop_images/Robotic_Arm__RM65-6F.png", category: "Industrial" },
  { name: "Robotic Arm (RM65-B)", image: "assets/products_shop_images/Robotic_Arm__RM65-B.png", category: "Industrial" },
  { name: "Robotic Arm (RM75-6F)", image: "assets/products_shop_images/Robotic_Arm__RM75-6F.png", category: "Industrial" },
  { name: "Robotic Arm (RM75-B)", image: "assets/products_shop_images/Robotic_Arm__RM75-B.png", category: "Industrial" },
  { name: "Robotic Arm (RML63-6F)", image: "assets/products_shop_images/Robotic_Arm__RML63-6F.png", category: "Industrial" },
  { name: "Robotic Arm (RML63-B)", image: "assets/products_shop_images/Robotic_Arm__RML63-B.png", category: "Industrial" },

  { name: "Single Arm Compound Robot - Precision, Mobility, and Versatility", image: "assets/products_shop_images/Single_Arm_Compound_Robot___Precision__Mobility__and_Versatility.png", category: "Industrial" },
  { name: "Single Arm Lifting Compound Robot", image: "assets/products_shop_images/Single_Arm_Lifting_Compound_Robot_1.png", category: "Industrial" },
  { name: "Single Arm Compound Robot - Compact, Mobile, and Intelligent Automation", image: "assets/products_shop_images/Single_Arm_Compound_Robot___Compact__Mobile__and_Intelligent_Automation.png", category: "Industrial" },

  { name: "Camera (D435C)", image: "assets/products_shop_images/Camera__D435C.png", category: "Accessories" },
  { name: "Camera (DaBai DCW)", image: "assets/products_shop_images/Camera__DaBai_DCW.png", category: "Accessories" },
  { name: "Flexible Gripper (RM-SFG)", image: "assets/products_shop_images/Flexible_Gripper__RM-SFG.png", category: "Accessories" },
  { name: "Gripper (EG2-SF16)", image: "assets/products_shop_images/Gripper__EG2-SF16__1.png", category: "Accessories" }
];
